De-emphasizing phones
FIRST-Tech-Challenge/ftcdocs pull request #294
Opened 2024-08-02 01:13 UTC by miriamsr

Resolves FIRST-Tech-Challenge/ftcdocs-private#106

2024-08-02 15:03 UTC, emcclurg commented
This looks good to me.  T

2024-08-21 17:31 UTC, miriamsr commented
@emcclurg Yes, I will get back to work on this, end of next week should be doable.

2024-12-18 19:58 UTC, emcclurg commented on docs/source/ftc_sdk/updating/ds_app/Updating-the-DS-App.rst
> +   1. REV Hardware Client (RHC)
Do you want these #'s indented to the same indent as the #'s above?

2024-12-18 20:03 UTC, emcclurg commented on docs/source/ftc_sdk/updating/ds_app/Updating-the-DS-App.rst
> +         Update Status of Phone
Smartphone

2024-12-18 21:01 UTC, emcclurg reviewed
I left a few comments in the files.  Looks great overall. A major improvement.

2024-12-18 21:12 UTC, emcclurg commented
@miriamsr @WestsideRobotics I've gone through each file with a few comments. I think the removal of rules can wait until next season.  As long as Chris agrees let's approve!

2024-12-21 17:57 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_dual_hubs/configuring-dual-hubs.rst
> +a single robot to two. See rule R701 for the full details.
Rephrase to not point to s specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:57 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_dual_hubs/configuring-dual-hubs.rst
> +       FIRST-approved 12V batteries, refer to the current Competition Manual,
Rephrase to not point to s specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:58 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_dual_hubs/configuring-dual-hubs.rst
> +       refer to the current Competition Manual, rule R704.
Rephrase to not point to s specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:58 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_external_webcam/configuring-external-webcam.rst
> +cameras for computer vision-related tasks. See rule R715 for the full details.
Agree with Elizabeth. 

Rephrase to not point to s specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:59 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_external_webcam/configuring-external-webcam.rst
> +Hub during a match. See rule R708 for the full details.
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:59 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_uvc_camera/configuring-uvc-camera.rst
> +cameras for computer vision-related tasks. See rule R715 for the full details.
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:59 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_uvc_camera/configuring-uvc-camera.rst
> +hub to make this connection. See rule R617 for the full details. If a
Rephrase to not point to s specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 17:59 UTC, rachmo commented on docs/source/hardware_and_software_configuration/configuring/configuring_uvc_camera/configuring-uvc-camera.rst
> +   Competition Manual. See rule R602 for the full details.
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 18:00 UTC, rachmo commented on docs/source/programming_resources/shared/configuring_android/Configuring-Your-Android-Devices.rst
> +The official rules of the *FIRST* Tech Challenge (see R707) require that
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 18:00 UTC, rachmo commented on docs/source/programming_resources/shared/required_materials/Required-Materials.rst
> +       phones. See rules R701 and R704 for the full details.
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.  

Suggest something like:

> Check the Robot Construction rules in the [Competition Manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual) for details.

2024-12-21 18:00 UTC, rachmo commented on docs/source/programming_resources/shared/required_materials/Required-Materials.rst
> +       us a select list of Android phones. See rule R901 for the full
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.

2024-12-21 18:00 UTC, rachmo commented on docs/source/programming_resources/shared/using_android_device/Using-Your-Android-Device.rst
> +smartphones to be used as a DRIVER STATION or ROBOT CONTROLLER. See rule
Rephrase to not point to a specific rule number. Rule numbers may shift year to year.

2025-01-24 15:11 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
>  The DRIVER STATION is sort of like a remote control that you might use
Suggest omitting "sort of", for more consistent language/tone of ftc-docs.

2025-01-24 15:16 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
> +While not reccomended, teams may opt to use an Android smartphone as either their
"recommended" is misspelled, but anyway I suggest omitting that opening phrase.  The actual status of smartphones is that they are optional, covered by "Teams may opt to...".  Some teams have a legitimate need or preference for smartphones.

2025-01-24 15:18 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
> +DRIVER STATION or ROBOT CONTROLLER. DRIVER STATION phones should have the FTC Driver
Suggest changing "either...or" to just "or".  As an alternate, add ", or both" after ROBOT CONTROLLER.

2025-01-24 15:24 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
>  autonomously during a match. Teams write “op modes” (which stand for
"OpModes"

2025-01-24 15:25 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
>  mode to perform certain tasks during a match.
OpMode

2025-01-24 15:25 UTC, WestsideRobotics commented on docs/source/programming_resources/shared/control_system_intro/The-FTC-Control-System.rst
>  *Blocks Programming Tool* to create their op modes. Teams can also
OpModes

2025-01-24 15:42 UTC, WestsideRobotics commented on docs/source/hardware_and_software_configuration/configuring/configuring_dual_hubs/configuring-dual-hubs.rst
> +Controller will controller through this portal to the individual Expansion
change "controller" to "communicate"

2025-01-24 15:45 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/android_studio/creating_op_modes/Creating-and-Running-an-Op-Mode-(Android-Studio).rst
> +configured for your REV Control Hub or REV Expansion Hub. Modify the code for the program
add Robotics?

2025-01-24 15:45 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/android_studio/creating_op_modes/Creating-and-Running-an-Op-Mode-(Android-Studio).rst
> +Congratulations! You ran your first java OpMode!
Java?

2025-01-24 15:49 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/android_studio/creating_op_modes/Creating-and-Running-an-Op-Mode-(Android-Studio).rst
>  simultaneously on the Logictech F310 controller to designate your
Logitech is misspelled.  Also, could consider mentioning the alternate button names on PS2-style gamepads.

2025-01-24 15:50 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/blocks/running_op_modes/Running-Your-Op-Mode.rst
>  connect a Logitech F310 gamepad to the DRIVER STATION. Note that you can
...or other approved...

2025-01-24 15:51 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/blocks/running_op_modes/Running-Your-Op-Mode.rst
>  button and the A button simultaneously on the Logitech F310
consider mentioning PS2-style button names?

2025-01-24 15:52 UTC, WestsideRobotics commented on docs/source/programming_resources/tutorial_specific/blocks/running_op_modes/Running-Your-Op-Mode.rst
> +   Note that the word "TeleOp" is short for "Tele-Operated" and it implies a driver controlled OpMode (i.e., an OpMode that gets input from a human driver).
Can omit the comma after i.e.

2025-01-25 03:52 UTC, uvidyadharan requested changes

2025-01-25 03:52 UTC, uvidyadharan commented on docs/source/conf.py
> +        ('hardware_and_software_configuration/configuring/managing_esd/managing-esd', 'esd.tex', 'Managind Electrostatic Discharge', author, "manual"), # ESD
Should be "Managing Electrostatic Discharge"

2025-02-03 21:10 UTC, texasdiaz approved these changes

2025-02-03 21:37 UTC, merged